### ISSUE TITLE
菜单使用动态标题则物品会闪烁

### ISSUE THREAD

**Issue by inrhor** [Arasple/Invero#12]
```yaml
title:
  mode: loop
  period: 2
  values:
  - '&{#ee4866}&l以物换物'
  - '&{#815c94}&l以&{#ee4866}&l物换物'
  - '&{#ee4866}&l以&{#815c94}&l物&{#ee4866}&l换物'
  - '&{#ee4866}&l以物&{#815c94}&l换&{#ee4866}&l物'
  - '&{#ee4866}以物换物'


layout: |-
  #########
  |   *   |
  |       |
  |   -   |
  #########

items:
  '*':
    material: book
    frames-prop:
      last: 3
      type: reversable
    frames:
      - name: S
      - name: St
      - name: Sto
      - name: Ston
      - name: Stone
```
