### ISSUE TITLE
图标数量错误

### ISSUE THREAD

**Issue by qaz197418i** [Arasple/Invero#16]
这是我菜单中的两个图标，图标'giftbox1'并没有设置数量，理论应该为1个，但是却显示为5个，但是当我将'giftbox1'的图标更改为ender_chest后，数量则正常，我怀疑这个错误可能与head类型图标有关，因为目前发现它只在head图标下会出现这个错误.
![image](https://github.com/Arasple/Invero/assets/30312760/79be24d8-6377-4dd4-829a-b57b54c3e5c7)
![image](https://github.com/Arasple/Invero/assets/30312760/b1addf23-9062-4959-97b1-fea8c43089c8)

```
  'giftbox1':
    head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZkNDUyODcwZDQ5MzcxOGViNjM2NDdhZDgwZTAwZjUwYjc3NDYwMWNiMDY3Nzc1ZjkwZmMxZWFhZGE4ZmNlZiJ9fX0=
    slot: 29
    name: '&c神秘箱'
    lore:
    - '&71个神秘箱'
    - ''
    - '&7价格: &c&m5宝石&b 4宝石'
    - ' &825%折扣！ (测试特惠)'
    - ''
    - '&c你的宝石不足.'
    action:
    - sound ENTITY_ENDERMEN_TELEPORT by 1 2
    - tell '&c你还需要&b%math_4-{playerpoints_points}%宝石&c才能购买！'
    sub:
      - condition: check papi "%playerpoints_points%" >= 4
        name: '&a神秘箱'
        lore:
        - '&71个神秘箱'
        - ''
        - '&7价格: &c&m5宝石&b 4宝石'
        - ' &825%折扣！ (测试特惠)'
        - ''
        - '&e点击购买商品！'
        action:
        - sound BLOCK_NOTE_HAT by 2 1
        - command 'abo edit storeitem mysterybox1 set %player_name%' as console
        - command 'abo edit storeprice 4 set %player_name%' as console
        - menu open buyconfirm
  'giftbox2':
    head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZkNDUyODcwZDQ5MzcxOGViNjM2NDdhZDgwZTAwZjUwYjc3NDYwMWNiMDY3Nzc1ZjkwZmMxZWFhZGE4ZmNlZiJ9fX0=
    slot: 30
    amount: 5
    name: '&c普通神秘箱组合包'
    lore:
    - '&7这个组合包包含5个神秘箱.'
    - ''
    - '&7价格: &c&m20宝石&b 15宝石'
    - ' &825%折扣！ (测试特惠)'
    - ''
    - '&c你的宝石不足.'
    action:
    - sound ENTITY_ENDERMEN_TELEPORT by 1 2
    - tell '&c你还需要&b%math_15-{playerpoints_points}%宝石&c才能购买！'
    sub:
      - condition: check papi "%playerpoints_points%" >= 15
        name: '&a普通神秘箱组合包'
        lore:
        - '&7这个组合包包含5个神秘箱.'
        - ''
        - '&7价格: &c&m20宝石&b 15宝石'
        - ' &825%折扣！ (测试特惠)'
        - ''
        - '&e点击购买商品！'
        action:
        - sound BLOCK_NOTE_HAT by 2 1
        - command 'abo edit storeitem mysterybox5 set %player_name%' as console
        - command 'abo edit storeprice 15 set %player_name%' as console
        - menu open buyconfirm
```
