### ISSUE TITLE
捕获器无法获取到捕获的内容

### ISSUE THREAD

**Issue by qaz197418i** [Arasple/Invero#18]
我尝试结合群里发的和例子来写捕获器功能，但是似乎捕获器无法正确捕获到内容，或者说捕获的内容无法成为变量
```
    action:
      reopen: false
      catch: name
      beforeInput: |
        tell "输入名称"
      afterInput: |
        tell "你输入了 {{&name}}"
```

在这段代码最后afterinput的tell内容里只有"你输入了"，并没有给出name变量的值，同样其他地方也无法调用到这个值
