### ISSUE TITLE
enhancedLore 无效果

### ISSUE THREAD

**Issue by postyizhan** [Arasple/Invero#21]
生成器中配置enhancedLore无效果
![图片](https://github.com/Arasple/Invero/assets/97342038/e2a82491-f1a2-4e58-87c2-ab28ff625f08)

QQ：185839426
核心：https://github.com/LeavesMC/Leaves
版本：1.19.4
插件：Invero-1.0.8-pre-3
日志：无报错
复现步骤：
>generator:
  elements:
    - prefix: 'VIP'
      show: '&aVIP'
      perm: group.vip
      lore: |-
        vip test
        123
    - prefix: 'SVIP'
      show: '&eSVIP'
      perm: group.svip
      lore: |-
        svip test
    - prefix: 'MVP'
      show: '&bMVIP'
      perm: group.mvp
      lore: |-
        mvip test

>  output:
    material: name_tag
    enhancedLore: true
    name: '{{&element_show}}'
    lore: |-
      &7称号
      {{&element_lore}}
    sub:
      - rule: check &player@prefix == &element_prefix
        glow: true
    action:
      context set player@prefix to &element_prefix
      icons refresh
      sound BLOCK_NOTE_BLOCK_PLING by 1 2

**Comment by Arasple** [comment]
```yaml
generator:
  elements:
    - prefix: 'VIP'
      show: '&aVIP'
      perm: group.vip
      lore: |-
        vip test 123
        \n第二行
        \n第三行
```

这个样子写能解决问题。暂时不考虑修复优化
